name: doarun
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  faunadb_http: ^0.13.1
  get: ^4.1.3
  flutter_spinkit: ^4.1.2
  flutter_svg: ^0.21.0+1
  lottie: ^1.0.1
  flutter_launcher_icons: ^0.9.0
  auto_size_text: ^2.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/doarun.png"

flutter_launcher_name:
  name: "Doarun"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Londrina
      fonts:
        - asset: assets/fonts/LondrinaSolid-Regular.ttf
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf