name: doarun
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.1.3
  flutter_spinkit: ^4.1.2
  flutter_svg: ^0.21.0+1
  lottie: ^1.0.1
  flutter_launcher_icons: ^0.9.0
  auto_size_text: ^2.1.0
  cloud_firestore: ^1.0.5
  firebase_auth: ^1.1.0
  google_sign_in: ^5.0.2
  shared_preferences: ^2.0.5
  firebase_core: ^1.0.3
  http: ^0.13.1
  flutter_web_auth: ^0.3.0
  flutter_flavorizr: ^2.0.0
  firebase_dynamic_links: ^2.0.4
  share: ^2.0.1
  firebase_analytics: ^7.0.1
  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ^0.3.0+2
  flutter_polyline_points: ^1.0.0

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Doarun dev"

      android:
        applicationId: "dev.doarun.app"
        firebase:
          config: "android/app/src/dev/google-services.json"

      ios:
        bundleId: "dev.doarun.app"

    beta:
      app:
        name: "Doarun beta"

      android:
        applicationId: "beta.doarun.app"
        firebase:
          config: "android/app/src/beta/google-services.json"
      ios:
        bundleId: "beta.doarun.app"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/doarun.png"

flutter_launcher_name:
  name: "Doarun"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Londrina
      fonts:
        - asset: assets/fonts/LondrinaSolid-Regular.ttf
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf